<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  win:
    roles:
      - windows
      - ad
    platform: windows-server-amd64
    box: opentable/win-2012r2-standard-amd64-nocm # VBOX ONLY
    hypervisor: <%= hypervisor %>
    vagrant_memsize: 2048
    vagrant_cpus: 2
    user: vagrant
    communicator: winrm
    is_cygwin: false
  centos7:
    roles:
      - default
      - client
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>
  centos6:
    roles:
      - client
    platform: el-6-x86_64
    box: centos/6
    hypervisor: <%= hypervisor %>
CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 256
<% if ENV['BEAKER_PUPPET_ENVIRONMENT'] -%>
  puppet_environment: <%= ENV['BEAKER_PUPPET_ENVIRONMENT'] %>
<% end -%>
