<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el7:
    roles:
      - el7
      - master
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>

  el8:
    roles:
      - el8
    platform: el-8-x86_64
    box: centos/8
    hypervisor: <%= hypervisor %>

  el8-0:
    roles:
      - el8
    platform: el-8-x86_64
    box: centos/8
    box_version: "1905.1"
    hypervisor: <%= hypervisor %>

CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 256
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
