---
HOSTS:
  el7:
    roles:
    - default
    - el7
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
  el8:
    roles:
    - el8
    platform: el-8-x86_64
    box: centos/stream8
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: centos-cloud/centos-stream-8
    gce_machine_type: n1-standard-2
CONFIG:
  multi_node: false
  log_level: verbose
  type: aio
  vagrant_cpus: 2
  ssh:
    keepalive: true
    keepalive_interval: 10
    host_key:
      - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:host_key].join("\n#{' '*6}- ") %>
    kex:
      - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:kex].join("\n#{' '*6}- ") %>
    encryption:
      - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:encryption].join("\n#{' '*6}- ") %>
    hmac:
      - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:hmac].join("\n#{' '*6}- ") %>
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'puppet7') %>"
